# db_lib.toml: mysql db

# Service Name
Name = "db_lib"

## not necessary
# ms
WriteTimeOut = 1000
# ms
ReadTimeOut = 500
# Retry num: total num of req = Retry + 1; database/sql has 2 intrinsic retry
Retry = 2

# Resource Ip Port
[Resource.Manual]
Host = "localhost"
Port = 3306

# mysql
[MySQL]
Username = "username_lib"
Password = "pwd_lib"
DBName = "db_lib"
DBDriver = "mysql"
Charset = "utf8"
Collation = "utf8_unicode_ci"
Timeout = 90000 # ms
SQLLogLen = -1 # print log, 0 means no, -1 means print all